on:
  push:
    branches: [main]
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: minecraft.flatpak
        manifest-path: org.lce4jcraft.minecraft.yml
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.variant.arch }}
