on:
  push:
    branches: [main]
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  pull_request:
  workflow_dispatch:
name: Flatpak
permissions:
  id-token: write
  contents: read
jobs:
  gnome-flatpak:
    name: "Flatpak"
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.lce4jcraft.minecraft.flatpak
          manifest-path: org.lce4jcraft.minecraft.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          restore-cache: true
          verbose: true
